apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: MY-APPLICATION-NAME
  namespace: argocd
spec:
  project: default
  source:
    repoURL: KUBERNETES-MANIFESTS-REPOSITORY-URL
    targetRevision: HEAD
    path: ./MY-FOLDER
  destination: 
    server: https://kubernetes.default.svc
    namespace: MY-NAMESPACE
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true