apiVersion: v1
kind: Secret
metadata:
 name: manifest-repository-access-secret
 namespace: argocd
 labels:
  argocd.argoproj.io/secret-type: repository
stringData:
 type: git
 url: KUBERNETES-MANIFESTS-REPOSITORY-URL
 username: REPOSITORY-USERNAME
 password: REPOSITORY-ACCESS-TOKEN
